# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: false
os:  linux
before_install:
    - sudo apt-get install libgsl0ldbl gsl-bin libgsl0-dev
 
