# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:  osx
warnings_are_errors: false
os:  linux
before_install:
    - apt-get install libgsl0ldbl gsl-bin libgsl0-dev
warnings_are_errors: false
 
